- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  notify:
    - nginx systemd

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Uninstall Apache2
  apt:
    name: apache2
    state: absent
    purge: yes

- import_tasks: php.yml
