---

- name: firewalld systemd restart
  command: firewall-cmd --reload

- name: grafana systemd
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: restart grafana
  become: true
  service:
    name: grafana-server
    state: restarted

- name: Set privileges on provisioned dashboards
  become: true
  file:
    path: "{{ grafana_data_dir }}/dashboards"
    recurse: true
    owner: grafana
    group: grafana
    mode: 0640
  listen: "provisioned dashboards changed"

- name: Set privileges on provisioned dashboards directory
  become: true
  file:
    path: "{{ grafana_data_dir }}/dashboards"
    state: directory
    recurse: false
    mode: 0755
  listen: "provisioned dashboards changed"
